### ISSUE TITLE
Antialising?

### ISSUE THREAD

**Issue by jens1o** [expenses/line_drawing#6]
Thanks for your crate, it is pretty useful. I wonder whether you have any tips on how to avoid hard edges?

**Comment by chitalian** [comment]
This is an old question. 

But you can use `line_drawing::XiaolinWu`

And do something like:
```rust
for ((x, y), alpha) in line_drawing::XiaolinWu::<f32, i32>::new(p_1, p_2) {
   //do stuff
}
```

**Comment by expenses** [comment]
yep, that's the idea.

**Comment by jens1o** [comment]
This is still relevant, thank you for the answer @chitalian :)

**Comment by chitalian** [comment]
No problem @jens1o 

I also made an example here: https://gitlab.com/justintorre75/image-examples

This may help

**Comment by Boscop** [comment]
@expenses I'm looking at the doc:
https://docs.rs/line_drawing/0.8.0/line_drawing/struct.XiaolinWu.html
Why are the first & last points `((0, 0), 0.5)` and `((3, 6), 0.5)` not fully covered (1.0)?
